var redirect_uri = 'http://localhost:3000/create-playlist';
var client_id = process.env.REACT_APP_SPOTIFY_ID;
var scope = 'playlist-modify-private';
export const authEndpoint = 'https://accounts.spotify.com/authorize'
export const loginUrl = `${authEndpoint}?
client_id=${client_id}
&redirect_uri=${redirect_uri}
&scope=${scope}
&response_type=token`